version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm run dev"
