# 「option+shit+p」 でviewを表示する

openapi: "3.0.3"

info:
  title: bambooGPT
  version: 1.0.0

paths:
  /api/login/google:
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                idToken:
                  type: string
                  example: "ej9G9geGfe93fbn28fnguucnuFuBUBW3482YFb3ffb"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Takeuchi Shuto"
                  image:
                    type: string
                    example: "https://lh3.googleusercontent.com/a/AGNmyxaSTIc2VT5hJCZhFLcFzucXrhLdwvCCCFvaLZPk=s96-c"
  /api/threads:
    post:
      summary: Create a new thread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                  example: "ASCcQXazh6rqxUdGdUNc"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  threadId:
                    type: string
                    example: "K230V3vZkEgDd9bL78zh"
                  name:
                    type: string
                    example: "My First Thread"
    get:
      summary: Get all threads
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    threadId:
                      type: string
                      example: "K230V3vZkEgDd9bL78zh"
                    name:
                      type: string
                      example: "My First Thread"

  /api/openai/chats:
    post:
      summary: Create a new chat
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                threadId:
                  type: string
                  example: "ASCcQXazh6rqxUdGdUNc"
                chat:
                  type: object
                  properties:
                    message:
                      type: array
                      items:
                        type: object
                        properties:
                          role:
                            type: string
                          content:
                            type: string
            example:
              value:
                message:
                  - role: system
                    content: "You are a helpful assistant."
                  - role: user
                    content: "Who won the world series in 2020?"
                  - role: assistant
                    content: "The Los Angeles Dodgers won the World Series in 2020."
                  - role: user
                    content: "Where was it played?"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                value: '{"text":"You are a helpful assistant."}\n{"text":"The Los Angeles Dodgers won the World Series in 2020."}\n{"text":"Where was it played?"}\n'
              encoding:
                message:
                  style: deepObject
                  explode: true
                  contentType: "application/x-ndjson"
